### ISSUE TITLE
Unable to run Allrun scripts

### ISSUE THREAD

**Issue by ashishmagar600** [philipmorrisintl/aerosolved#2]
I am not able to run much of the tutorials which are using bash scripting and variables for changing entries in the dicts. 
For cases/Brownian:
`$> ./Allrun`

`Invalid aerosol model specified (sectional or moment)
`

Do we have to do something else before running the Allrun script? 

I am able to run just the cases/cavity with scripts.

**Comment by f-lucci** [comment]
sectional or moment needs to be  an input of the Allrun script.

Type for exhample:

> ./Allrun moment

**Comment by ashishmagar600** [comment]
Thank you.

For cases/CAG:
`$> ./Allrun 20 moment`
`./Allrun: 10: ./Allrun: [[: not found
Invalid mesh (specify the radial number of cells in the capillary)
`
should be the command? Where '20' is the radial number of cells in the capillary.

Also for cases/elbow:
`$> ./Allrun fullStokes moment` 
`./Allrun: 8: ./Allrun: Syntax error: "(" unexpected (expecting "then")
`

**Comment by ashishmagar600** [comment]
Is there any correct way to run them?

**Comment by bluelee333633** [comment]
bash ./allrun

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ashishmagar600** [comment]
Thank You..!!

**Comment by leecking** [comment]
Have you solved your problem? Can you tell me the method?

**Comment by ohohohvv** [comment]
I need the method too!!
