### ISSUE TITLE
How to run the cases

### ISSUE THREAD

**Issue by greffinea** [philipmorrisintl/aerosolved#6]
Hi!
I am a new guy, I use (like icoFoam) to run the case,but I can't use aerosolEulerFoam. I also use ./Allrun  fullStokes sectional ,it dosen't work.I hope you give me some advice or more details.
Thanks very much!

**Comment by mabelqiao** [comment]
Hi, I wonder if you managed to successfully use the ./Allrun command? I also got an error.
